-- =============================================
-- SeniorCare 데이터베이스 스키마 (Oracle)
-- =============================================

-- 시퀀스 생성
CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MEDICATION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SCHEDULE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE CARE_REQUEST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE CAREGIVER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE GUARDIAN_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE INVITATION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 사용자 테이블
CREATE TABLE USERS (
    USER_ID         NUMBER PRIMARY KEY,
    EMAIL           VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD        VARCHAR2(255),
    NAME            VARCHAR2(50) NOT NULL,
    PHONE           VARCHAR2(20),
    ROLE            VARCHAR2(20) NOT NULL,          -- SENIOR, CHILD (자녀)
    PROVIDER        VARCHAR2(20) DEFAULT 'LOCAL',   -- LOCAL, KAKAO, NAVER
    PROVIDER_ID     VARCHAR2(100),
    PROFILE_IMAGE   VARCHAR2(500),
    CREATED_AT      TIMESTAMP DEFAULT SYSDATE,
    UPDATED_AT      TIMESTAMP DEFAULT SYSDATE
);

CREATE INDEX IDX_USERS_EMAIL ON USERS(EMAIL);
CREATE INDEX IDX_USERS_PROVIDER ON USERS(PROVIDER, PROVIDER_ID);

-- 약 정보 테이블
CREATE TABLE MEDICATIONS (
    MEDICATION_ID   NUMBER PRIMARY KEY,
    USER_ID         NUMBER NOT NULL,
    NAME            VARCHAR2(100) NOT NULL,
    DOSAGE          VARCHAR2(100),
    DESCRIPTION     VARCHAR2(500),
    START_DATE      DATE,
    END_DATE        DATE,
    CREATED_AT      TIMESTAMP DEFAULT SYSDATE,
    UPDATED_AT      TIMESTAMP DEFAULT SYSDATE,
    CONSTRAINT FK_MED_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_MED_USER ON MEDICATIONS(USER_ID);

-- 복용 스케줄 테이블
CREATE TABLE MEDICATION_SCHEDULES (
    SCHEDULE_ID     NUMBER PRIMARY KEY,
    MEDICATION_ID   NUMBER NOT NULL,
    SCHEDULED_TIME  VARCHAR2(5) NOT NULL,           -- HH:MM 형식
    DAY_OF_WEEK     VARCHAR2(10) NOT NULL,          -- DAILY, MON, TUE, ...
    TAKEN           NUMBER(1) DEFAULT 0,            -- 0: 미복용, 1: 복용
    TAKEN_AT        TIMESTAMP,
    CREATED_AT      TIMESTAMP DEFAULT SYSDATE,
    CONSTRAINT FK_SCHED_MED FOREIGN KEY (MEDICATION_ID) REFERENCES MEDICATIONS(MEDICATION_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_SCHED_MED ON MEDICATION_SCHEDULES(MEDICATION_ID);

-- 돌보미 프로필 테이블
CREATE TABLE CAREGIVERS (
    CAREGIVER_ID     NUMBER PRIMARY KEY,
    USER_ID          NUMBER NOT NULL UNIQUE,
    SPECIALIZATION   VARCHAR2(200),
    CERTIFICATION    VARCHAR2(200),
    EXPERIENCE_YEARS NUMBER,
    INTRODUCTION     VARCHAR2(1000),
    AVAILABLE_AREA   VARCHAR2(200),
    RATING           NUMBER(3,2) DEFAULT 0,
    REVIEW_COUNT     NUMBER DEFAULT 0,
    CREATED_AT       TIMESTAMP DEFAULT SYSDATE,
    UPDATED_AT       TIMESTAMP DEFAULT SYSDATE,
    CONSTRAINT FK_CG_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 돌봄 요청 테이블
CREATE TABLE CARE_REQUESTS (
    REQUEST_ID      NUMBER PRIMARY KEY,
    SENIOR_ID       NUMBER NOT NULL,
    CAREGIVER_ID    NUMBER,
    CARE_TYPE       VARCHAR2(20) NOT NULL,           -- DAILY, MEDICAL, COMPANION
    DESCRIPTION     VARCHAR2(500),
    REQUESTED_DATE  DATE,
    START_TIME      VARCHAR2(5),                     -- HH:MM
    END_TIME        VARCHAR2(5),                     -- HH:MM
    STATUS          VARCHAR2(20) DEFAULT 'PENDING',  -- PENDING, ACCEPTED, REJECTED, COMPLETED, CANCELLED
    ADDRESS         VARCHAR2(300),
    CREATED_AT      TIMESTAMP DEFAULT SYSDATE,
    UPDATED_AT      TIMESTAMP DEFAULT SYSDATE,
    CONSTRAINT FK_CR_SENIOR FOREIGN KEY (SENIOR_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_CR_CG FOREIGN KEY (CAREGIVER_ID) REFERENCES CAREGIVERS(CAREGIVER_ID)
);

CREATE INDEX IDX_CR_SENIOR ON CARE_REQUESTS(SENIOR_ID);
CREATE INDEX IDX_CR_CG ON CARE_REQUESTS(CAREGIVER_ID);
CREATE INDEX IDX_CR_STATUS ON CARE_REQUESTS(STATUS);

-- 보호자 연동 테이블
CREATE TABLE GUARDIANS (
    GUARDIAN_ID       NUMBER PRIMARY KEY,
    GUARDIAN_USER_ID  NUMBER NOT NULL,
    SENIOR_USER_ID    NUMBER NOT NULL,
    RELATIONSHIP      VARCHAR2(20),                  -- CHILD, SPOUSE, SIBLING, OTHER
    STATUS            VARCHAR2(20) DEFAULT 'PENDING', -- PENDING, ACCEPTED, REJECTED
    CREATED_AT        TIMESTAMP DEFAULT SYSDATE,
    UPDATED_AT        TIMESTAMP DEFAULT SYSDATE,
    CONSTRAINT FK_GD_GUARDIAN FOREIGN KEY (GUARDIAN_USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_GD_SENIOR FOREIGN KEY (SENIOR_USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT UQ_GUARDIAN_SENIOR UNIQUE (GUARDIAN_USER_ID, SENIOR_USER_ID)
);

CREATE INDEX IDX_GD_GUARDIAN ON GUARDIANS(GUARDIAN_USER_ID);
CREATE INDEX IDX_GD_SENIOR ON GUARDIANS(SENIOR_USER_ID);

-- 초대 링크 테이블 (자녀가 어르신에게 보내는 초대)
CREATE TABLE INVITATIONS (
    INVITATION_ID    NUMBER PRIMARY KEY,
    INVITE_CODE      VARCHAR2(50) NOT NULL UNIQUE,      -- 고유 초대 코드
    INVITER_USER_ID  NUMBER NOT NULL,                   -- 초대한 사람 (자녀)
    INVITEE_PHONE    VARCHAR2(20),                      -- 초대받은 사람 전화번호 (어르신)
    INVITEE_USER_ID  NUMBER,                            -- 초대받은 사람이 가입 후 연결
    RELATIONSHIP     VARCHAR2(20) DEFAULT 'CHILD',      -- CHILD, SPOUSE, SIBLING, OTHER
    STATUS           VARCHAR2(20) DEFAULT 'PENDING',    -- PENDING, ACCEPTED, EXPIRED
    EXPIRED_AT       TIMESTAMP,
    CREATED_AT       TIMESTAMP DEFAULT SYSDATE,
    CONSTRAINT FK_INV_INVITER FOREIGN KEY (INVITER_USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_INV_INVITEE FOREIGN KEY (INVITEE_USER_ID) REFERENCES USERS(USER_ID)
);

CREATE INDEX IDX_INV_CODE ON INVITATIONS(INVITE_CODE);
CREATE INDEX IDX_INV_INVITER ON INVITATIONS(INVITER_USER_ID);
CREATE INDEX IDX_INV_PHONE ON INVITATIONS(INVITEE_PHONE);
